import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import AuthenticatedNavbar from "@/components/layout/AuthenticatedNavbar";
import AuthenticatedFooter from "@/components/layout/AuthenticatedFooter";
import { AuthProvider } from "@/lib/auth/authContext";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen bg-black text-white pb-24">
          <AuthProvider>
            <AuthenticatedNavbar />
            {children}
            <AuthenticatedFooter />
          </AuthProvider>
        </div>
      </body>
    </html>
  );
}
