# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.NET Core API to Azure Web App - tallyprs

on:
  push:
    branches:
      - master
    paths:
      - 'tallyprs-api/**'
      - '.github/workflows/master_tallyprs.yml'
  workflow_dispatch:

env:
  API_PROJECT_PATH: tallyprs-api/TallahasseePRs.Api.csproj
  PUBLISH_DIR: ${{ github.workspace }}/publish

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Restore API
        run: dotnet restore ${{ env.API_PROJECT_PATH }}

      - name: Build API
        run: dotnet build ${{ env.API_PROJECT_PATH }} --configuration Release --no-restore

      - name: Publish API
        run: dotnet publish ${{ env.API_PROJECT_PATH }} --configuration Release --no-build --output ${{ env.PUBLISH_DIR }}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ env.PUBLISH_DIR }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EF2BFADD9B854CCDB7471829B76D1A6E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_DB6EF3E612854239815FD2A0DD48B595 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7012B1DE7AFE4578BA77B74073A4FEA7 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tallyprs'
          slot-name: 'Production'
          package: .
